### ISSUE TITLE
Explore Gempa's event correction step during antelope event conversion

### ISSUE THREAD

**Issue by basaks** [GeoscienceAustralia/passive-seismic#13]

**Comment by basaks** [comment]
Gempa has proposed a correction on top of our antelope to sc3 xml coversion as detailed here: https://github.com/GeoscienceAustralia/passive-seismic/tree/master/antelope.

@niketchhajed Please follow up with @gasuperdev . He has details.

**Comment by niketchhajed** [comment]
This correction was discussed with Simon. It was found that the proposed correction was required when using scdispatch which interacts with the messaging system which in turn interacts with the DB. Our usecase requires the alternate tool scdb which directly interacts with the DB in offline mode. Prima facie, this correction doesn't seem to be applicable to us at this time.

Will come back to this, if required in future.
