### ISSUE TITLE
convert and ingest ENGDAHL events into seiscomp3

### ISSUE THREAD

**Issue by basaks** [GeoscienceAustralia/passive-seismic#23]
These are the events that @alexgorb passed onto us in text files.

**Comment by niketchhajed** [comment]
Currently, looking at the files received from @alexgorb and analysing them for migration to Siescomp3. The goal is to interpret the data files and map their schema to Seiscomp3 database schema as much as possible. If there are any missing fields, erroneous data or conflicting fields, the same needs to be reported and mitigated.

**Comment by niketchhajed** [comment]
We have 3 types of files: DAT files, HDF files and OUT files. As per discussion with Alexei, the DAT files, which are in the FFB format (Fixed Format Bulletin) need to be parsed and the pick, origin, amplitude, magnitude and event information needs to be extracted. The extracted data needs to be massaged into the FDSNXML format that can be imported into the SC3 DB. The public ID information needs to be synthetically created and added to the resulting FDSNXML file before importing to the SC3 DB.

The FFB format is described at: http://www.isc.ac.uk/standards/ffb/

After goinf through the Projet Report pdf file, the HDF and OUT files seem to be downstream files as a result of processing by ENGDAHL.

**Comment by niketchhajed** [comment]
Pasting some notes while discussing with Alexei:

origin:
1. lat lon depth Agency OriginTime Magnitude TP mthodID(EHB) earthModelID(ak135) <quality>
        <associatedPhaseCount>9</associatedPhaseCount>
        <usedPhaseCount>7</usedPhaseCount>
        <associatedStationCount>9</associatedStationCount>
        <usedStationCount>7</usedStationCount>
        <standardError>3.030084268</standardError>
        <azimuthalGap>149.6036987</azimuthalGap>
        <maximumDistance>15.91859436</maximumDistance>
        <minimumDistance>4.030264378</minimumDistance>
        <medianDistance>7.434346199</medianDistance>
      </quality>

evaluationMode(automatic) <creationInfo>
        <agencyID>NA</agencyID>
        <author>scautoloc@ip-172-31-30-172</author>
        <creationTime>2017-10-19T07:14:16.002041Z</creationTime>
      </creationInfo>

(if no residual, it was not used for location but only for association)

pick:
1. phase Net Sta Channel Res Dis(deg) Az(or backazimuth) Time methodID(default to STA/LTA) evaluationMode(automatic) author(EHB)

**Comment by basaks** [comment]
@niketchhajed As discussed,  here is a approach that might work.
We should try and create `obspy` event objects for each event and `obspy` has event export functionality into `quakeml` and also `sc3ml`.

See how I create `picks` and `amplitude` obspy objects in [seismic.pickers.PickerMixin class](https://github.com/GeoscienceAustralia/passive-seismic/blob/master/seismic/pickers.py#L39). We need to be able to further create the rest of the objects that are required by the event class, e.g., [here](https://docs.obspy.org/packages/obspy.core.event.html). Then we can dump a `SC3ML`/`quakeml` that can be ingested into `seiscomp3`.

For [`PhasePApy`](https://github.com/GeoscienceAustralia/PhasePApy), @sudhirjain may have to pursue a similar approach.

**Comment by niketchhajed** [comment]
In further discussion with Alexei, he has agreed that the relocated data files .HDF and .OUT is what needs to be considered for importing into SC3 db.

Given the fact that in .DAT files, there are 5 sec differences in arrival times for the same station between those received by GA stations and those received by ISC from other sources, importing from .DAT would probably not be the best idea. The .HDF and .OUT files have data that has relocated origins and relocated arrival times. These will be imported in SC3.

**Comment by niketchhajed** [comment]
Still there are some grey areas in the .HDF and .OUT files as described below:

1. In .OUT files, for the same P arrival, there are multiple phase labels i.e. P, Pn, eP, iP, PP, PnPn, PcP, Pdiff, PKiKP, ePKP, ePKI, PKP, pP, epP, etc. These notations need to be clarified.
2. In .OUT file, there is LR P arrival notation which, as per @alexgorb, is for surface wave which should be able to ignore, post confirmation from @alexgorb. 
3. In the .HDF file, there are 2 columns: ntot(total number of observations used) and ntel(number of teleseismic observations used - delta > 28 deg). The arrival data in .OUT files needs to be correlated with the values in these 2 columns, to establish which arrivals were used for association and which were used for location. Need more clarification from @alexgorb on this.

**Comment by alexgorb** [comment]
1. There are many different phases (http://www.isc.ac.uk/standards/phases/)  and all are required for our purposes. However the first characters such as 'e' or 'i' corresponds to the energy of the arrival phase - emergent or impulsive. These characters usually omitted during conversions if can not be transferred into separated field of new format.
2. It is not very clear to me. I would say that these numbers are only for model selection purposes and do not have any relation to association or location.

**Comment by niketchhajed** [comment]
I have listed below some clarifications required from @alexgorb:

1. There are more than a million unique stations involved in arrivals in the ENGDAHL files. However, the network code information is missing. Is there an easy way to uniquely determine the network code for a given station name?
2. In the .out file, most of the S arrivals have the station name missing. Like below:

  date   sta  delta  dtdd     backaz      focal angle    fm  phase               hr min sec  residual  pP   pwP  sP  PcP scor  wgt
                                           dip      az
  5 916 JOW   39.11   8.36    237.06     29.40     48.64     P        P     P    17 26 52.86  -0.32                       0.3  0.9  
  5 916 NWAO  40.35   8.28    326.50     29.08    152.32     P        P     P    17 27  3.76   1.20                      -0.4  0.9  
  5 916 HHC   40.68   8.25    203.84     28.99     17.87  +  P       iP    iP    17 27  7.10   0.78                       0.6  0.9  
                                                             PP       PP    PP   17 28 45.00   4.36*                      0.6  0.0  
                                                             PcP      PcP   PCP  17 29  8.40  -0.36*                -0.4  1.5  0.0  
                                                                            SCP  17 32 55.10  -1.34*                      1.5  0.0  
                                                                            PCS  17 32 58.50   2.06*                      1.5  0.0  
                                                             S        S     S    17 33 15.10  -0.56                       1.5  0.1  
                                                             SS       SS    SS   17 36 10.30  -6.90*                      1.5  0.0  
                                                             ScS      SCS   SCS  17 37  8.60  -1.27*                      0.6  0.0  

Do we assume that the station name (and other details) for all S arrivals is the same as the P arrival immediately before?

3. How to process for arrivals that have the first (and second) phase missing. For e.g. the SCP or PCS arrival above.

4. One of the desired fields as part of the arrival information is distance. Is the delta field the same as the required distance field? It would be better if we can get the meaning of all columns listed below:

delta, dtdd, focal angle, (the missing column names for the 2 phases), scor, wgt( whether it is time weight or backazimuth weight?)

**Comment by niketchhajed** [comment]
![arrivals](https://user-images.githubusercontent.com/8789808/32255448-bf20507a-bef3-11e7-9c95-a5c03b81f8c3.jpg)

**Comment by alexgorb** [comment]
Later phases that come without station name (blank fields) correspond to the first station located above these lines. In this particular case to HHC

**Comment by alexgorb** [comment]
Please note - some stations may have only "later" phases such as PKP because no P wave present at long distances.

**Comment by alexgorb** [comment]
I checked the list of registered seismic stations. There are less than 1600 stations. @niketchhajed how did you calculate more than a million? See attached file.
[fdsnsta2013.zip](https://github.com/GeoscienceAustralia/passive-seismic/files/1435916/fdsnsta2013.zip)

**Comment by niketchhajed** [comment]
[allstations.txt](https://github.com/GeoscienceAustralia/passive-seismic/files/1436123/allstations.txt)

@alexgorb  This is the list of unique stations that are involved in the arrival data of ENGDAHL. If you find that something is not write in this list of stations, let me know. I will investigate.

**Comment by alexgorb** [comment]
So far I found that there are many duplicates and names such as one character (that can not be the name of station).
We need to benchmark against the list I sent you.

**Comment by niketchhajed** [comment]
Some more feedback from @alexgorb:

1. magnitude integration
2. distance (and other fields) for s phase the same as the immediately preceding p phase
3. include the entire phase and not the first character

**Comment by niketchhajed** [comment]
The current state of data migration was reviewed with @alexgorb and it seems to be in an acceptable condition. Below are the points to be worked upon but not urgent:

1. Integrate the network codes with the data.

Closing this issue and creating a separate issue for network codes integration.

**Comment by Zephyrpony** [comment]
Jira Task PST-215
https://gajira.atlassian.net/browse/PST-215

**Comment by niketchhajed** [comment]
The engdahl events are backed up at s3://pyrobots-backup/niket/engdahl-events/

**Comment by basaks** [comment]
Command to copy s3 dir using aws cli: `aws s3 cp s3://pyrobots-backup/niket/engdahl-events/ target_dir/ --recursive`.

**Comment by basaks** [comment]
All engdahl and isc events from the sc3 bucket are also copied in NCI here with read access for everyone: `/g/data/ha3/sudipta/event_xmls`.

**Comment by niketchhajed** [comment]
@basaks, just fyi. these isc events do not have preferred origin set. The ones with preferred origin set are currently in an AWS instance. I will replace the latest in S3.
