### ISSUE TITLE
Generate list of stations in ISC events not found in ISC station files and not found in our seiscomp3

### ISSUE THREAD

**Issue by basaks** [GeoscienceAustralia/passive-seismic#45]
There are many such stations that are not present in the ISC stations list and also in our seiscomp3. We can ignore the arrivals from these stations as we have millions of arrivals, but this is something we can contribute back to ISC for their cooperation.

**Comment by alexgorb** [comment]
What about IRIS and FDSN ?
IRIS has large database of seismic stations:
http://www.fdsn.org/networks/

**Comment by basaks** [comment]
@alexgorb agree, we should check iris and fdsn when we generate that list, something that I am not doing yet. May that should be done as part of this issue.

**Comment by basaks** [comment]
Jira: https://gajira.atlassian.net/browse/PST-233
