### ISSUE TITLE
`zone`ing functionality after `cluster`ing 

### ISSUE THREAD

**Issue by basaks** [GeoscienceAustralia/passive-seismic#52]
@alexgorb 

We need separate clustered datafile into 3 files:
* one for regional, 
* second which intersect area, and 
* other with global data

Region can be specified like the following:
```
upperlat = 90.
bottomlat= 50.
leftlon  = 240.
rightlon = 280.
```

**Comment by basaks** [comment]
@alexgorb regional and global zones are now working with well tested code (# f2f67c791c). 
I have not managed to work on the intersect region yet. 

This should be enough to test inversion for now?

**Comment by alexgorb** [comment]
Yes, lets try with regional and direct waves.

**Comment by basaks** [comment]
`Zones` can now be computed. `Region` and `global` zones are well tested. 
TODO: tests for `cross-region`/ `intersect area`

**Comment by basaks** [comment]
Closing this as this is quite old now. The cross-region/intersect remaining work has a new issue to track this: #63.

All the work done as part of this is merged into master.
