### ISSUE TITLE
picker for P & S waves

### ISSUE THREAD

**Issue by basaks** [GeoscienceAustralia/passive-seismic#6]
- [ ] Picking alogirthms and parameters must be user configurable.
- [ ] Automated by event id. Event id to be pulled from seiscomp3, miniseed dumped, p and s picked and saved to seiscomp3 database as a new event to be used by iLoc.

**Comment by basaks** [comment]
Intermediate output for [this event](https://github.com/GeoscienceAustralia/passive-seismic/blob/534cc86786435b8b43351c11ef8038a91b60c62d/tests/mocks/events/analyst_event_samples/772009.xml) attached.
[selected_stations.txt](https://github.com/GeoscienceAustralia/passive-seismic/files/1645410/selected_stations.txt)

**Comment by basaks** [comment]
So when `phase_hint` is empty, we need those phases picked.
Also expect a `phase_hint` value of, for example, `P & S` in case a station has both P and S picked. This does not happen for this event though.

**Comment by basaks** [comment]
We can use the `sta-network-channel-time` information for additional picks from this output format:

```
station_code,latitude,longitude,elevation,network_code,delta,arrival
BNDI,-4.5224,129.9045,16.0,GE,55.87159813950957,
GENI,-2.5927,140.1678,47.0,GE,49.16890868109843,
SANI,-2.0496,125.9881,30.0,GE,60.48381494431553,
AAI,-3.6871,128.1943,157.2,IA,57.73860229565345,
BAKI,-1.19145,136.10702,89.0,IA,53.133115288792744,
MMPI,-8.5181,140.4141,98.57,IA,45.15213780775282,
PCI,-0.9054,119.8366,150.0,IA,66.12607841051536,
SWI,-0.8628,131.2592,128.88,IA,57.05421517155677,
TLE,-5.6373,132.7373,113.0,IA,52.94563380816238,
WSI,-9.6689,120.29766599999999,48.0,IA,60.86592388179703,
APZ,-46.831806,167.988825,601.0,NZ,17.762728434732757,"{'P': {'time': UTCDateTime(2014, 2, 20, 5, 22, 26, 448000), 'channel': 'HHZ'}}"
DCZ,-45.464713,167.153533,71.0,NZ,17.17498206558948,
ARMA,-30.4198,151.628,1112.0,AU,25.73460714331225,"{'P': {'time': UTCDateTime(2014, 2, 20, 5, 23, 50, 517000), 'channel': 'BHZ'}}"
ARMA,-30.4183,151.6293,1112.0,AU,25.733840112198838,"{'P': {'time': UTCDateTime(2014, 2, 20, 5, 23, 50, 517000), 'channel': 'BHZ'}}"
ARPS,-36.7699,141.8383,213.0,AU,32.90861887097992,
BBOO,-32.8096,136.0583,295.0,AU,38.19583509066251,"{'P': {'time': UTCDateTime(2014, 2, 20, 5, 25, 36, 770000), 'channel': 'BHZ'}}"
BBOO,-32.8102,136.0588,321.0,AU,38.19529552752061,"{'P': {'time': UTCDateTime(2014, 2, 20, 5, 25, 36, 770000), 'channel': 'BHZ'}}"station_code,latitude,longitude,elevation,network_code,delta,phase_hint
BNDI,-4.5224,129.9045,16.0,GE,55.87159813950957,
GENI,-2.5927,140.1678,47.0,GE,49.16890868109843,
SANI,-2.0496,125.9881,30.0,GE,60.48381494431553,
```
[Attached complete .csv file](https://github.com/GeoscienceAustralia/passive-seismic/files/1650315/selected_stations.txt) for [this event](https://github.com/GeoscienceAustralia/passive-seismic/blob/534cc86786435b8b43351c11ef8038a91b60c62d/tests/mocks/events/analyst_event_samples/772009.xml).

**Comment by niketchhajed** [comment]
The development work for s-phase picking and updating the event xmls with newly added picks and arrivals to the preferred origin is complete. We are getting decent results on the March 2015 dataset and the s-picks can be viewed on plotting the waveform (a window around the event) after cleaning it with "best" calculated bandpass filter.

As a test case, the next step is to ingest these events into an SC3 instance having the March 2015 waveform data and inventory data and visually validate if the new s-picks "make sense".

**Comment by niketchhajed** [comment]
Next week, this will be validated with @alexgorb and this task will be closed after confirmation.

**Comment by niketchhajed** [comment]
Out of the 136 analyst reviewed events for March 2015, 61 of them had a positive result of extracting s-phase arrivals. These event xmls were then enhanced with newly extracted picks/arrivals and were re-ingested into a fresh SC3 instance. The same has been shared with @alexgorb and the team. Feedback on the same is requested to better tune the algorithm. However, based on a sanity check of visualizing the waveform at the reported times for p and s phases, the results seem to be good. The channel, residual and azimuth values for the arrivals are also available.

**Comment by niketchhajed** [comment]
fyi @alexgorb with reference to page 16 of the pdf doc at https://www.google.com.au/url?sa=t&source=web&rct=j&url=https://www.seis.sc.edu/downloads/TauP/taup.pdf&ved=2ahUKEwjLuZ-V1LLZAhUGfLwKHXnZAgYQFjAAegQIBhAB&usg=AOvVaw1FOpaPSXEG9jrIS89dsW__ there are 2 types of phases described, S and s:

S shear wave, upgoing or downgoing, in the crust or mantle
s strictly upgoing S wave in the crust or mantle

In the s-phase picking algorithm we implemented, we are currently averaging out the theoretical travel time between all phases that are either S or s. In order to improve residual calculation, we could make more deterministic decisions based on the phase of interest between the 2 or add weight age or such ...

**Comment by niketchhajed** [comment]
the s-picks on the limited dataset of March 2015 were validated with @alexgorb and the results seem to be satisfactory from a geologist's point of view. as per feedback, the next steps are:

1. run it on a larger dataset and validate results
2. experiment with an advanced picker like AIC
3. try extracting additional phases described at: http://www.isc.ac.uk/standards/phases/

closing this ticket and opening another task for the next steps.
