### ISSUE TITLE
Follow up actions from preliminary inversion work

### ISSUE THREAD

**Issue by basaks** [GeoscienceAustralia/passive-seismic#61]
From a preliminary inversion result, @alexgorb would like to re check the following:

- [ ] too many rays coming from certain location that shouldn’t be the case of summary rays.
- [x] coordinates of stations are correctly propagated to the inversion input files.
- [x] Further, "we need some statistic on Australian stations – which have been used and how many rays on each of them."

**Comment by basaks** [comment]
@alexgorb This function is used to check `region`  and `global` `zone` outputs to make sure that the stations indeed match those of the input stations:  
https://github.com/GeoscienceAustralia/passive-seismic/blob/d51c33ad98eacd97072a25d5fd24d558ebb2ac45/tests/test_cluster.py#L290

To be able to do that I also output a list of stations from which the arrivals came from during the batch `cluster gather` job now.  This list of participating stations will be further used for statistics on stations.

**Comment by basaks** [comment]
@alexgorb , `cluster zone` command now produces stats for participating stations (by default, which can be turned off) in this format:

```
station_code,station_longitude,station_latitude,frequency
ARU,58.562,56.4295,2
ASAR,133.904,-23.6662,1
BJI,116.175,40.0395,4
CD2,103.758,30.9094,5
CLNS,124.893,56.8365,1
CN2,125.448,43.8002,5
CNB,149.363,-35.3143,1
COEN,143.175,-13.9568,2
CTA,146.254,-20.0878,3
```
The last column, frequency, is the number of rays on the station. This output is produced for the input file for `zone`ing and also the in `region` and the complementary `global` region. Well tested code as well.

The first item here `too many rays coming from certain location that shouldn’t be the case of summary rays`, seems we need to do the same for `source` locations instead of stations.

**Comment by alexgorb** [comment]
There should be one ray between a pair of cells (source – receiver).
We can not reduce other number of rays

**Comment by basaks** [comment]
@alexgorb ,
>There should be one ray between a pair of cells (source – receiver). We can not reduce other number of rays

This is already the case and has been thoroughly tested [via this test](https://github.com/GeoscienceAustralia/passive-seismic/blob/fdfb577cab7fdaea8e9efadd4150983f32ae457b/tests/test_cluster.py#L384), [and specifically by this line.](https://github.com/GeoscienceAustralia/passive-seismic/blob/fdfb577cab7fdaea8e9efadd4150983f32ae457b/tests/test_cluster.py#L399).

This then makes that check complete?

**Comment by alexgorb** [comment]
I think it is. Please change “frequency” to “number of summary rays”

**Comment by basaks** [comment]
[Done. ](https://github.com/GeoscienceAustralia/passive-seismic/commit/9c6c2f168c623e5457e6c37465da60355fb50b73).

Here is the latest output format:

```
station_code,station_longitude,station_latitude,no_of_summary_rays
ARU,58.562,56.4295,2
ASAR,133.904,-23.6662,1
BJI,116.175,40.0395,4
CD2,103.758,30.9094,5
CLNS,124.893,56.8365,1
CN2,125.448,43.8002,5
CNB,149.363,-35.3143,1
COEN,143.175,-13.9568,2
CTA,146.254,-20.0878,3
```
