### ISSUE TITLE
During clustering use inversion parameter file as inputs

### ISSUE THREAD

**Issue by basaks** [GeoscienceAustralia/passive-seismic#64]
@alexgorb would like a depth filter implemented for `zone`ing in line with lat/lon based `zone`s..

**Comment by alexgorb** [comment]
Can you specify what you mean, please.

**Comment by basaks** [comment]
@alexgorb This is based on out discussion regarding the `z` range during clustering. Did I get that right?

How would you do this?

**Comment by alexgorb** [comment]
I do not understand and this is the reason why I ask. We talked about using inversion parameter file to define clustering

**Comment by basaks** [comment]
@alexgorb OK, so we are to read the `region` extent from the inversion parameter file. We don't need to change the grid size or the implement a `z` filter. 

I will change the scope of this issue accordingly.

**Comment by basaks** [comment]
This is done in  # eae922c3fe.

Now either a region sting of the form '0 -50.0 100 190' or a parameter file (same file as used during inversion) can be provided to read `region` extents during `cluster zone` operation. If both are provided, the parameter file is favored.
