### ISSUE TITLE
Analyst events not reported with `hypocenter`s

### ISSUE THREAD

**Issue by basaks** [GeoscienceAustralia/passive-seismic#66]
None of the analyst events were processed due to a `obspy` not recognizing the analyst reported `event_type`.

The problem was the `origin_type` field was not set properly in the analyst events. Origin type in `obspy` is limited to these values: "hypocenter", "centroid", "amplitude", "macroseismic", "rupture start", "rupture end".

The origin type in the analyst events were all set to `not reported` instead, obspy did not recognize that, and we have exception handling for such situations.

We will have to hack `obspy` to make this work.

**Comment by niketchhajed** [comment]
Please replace not reported with hypocenter in all event files.

**Comment by niketchhajed** [comment]
All analyst reported events are now available in Seiscomp3 ingestable format in NCI at: /g/data/ha3/events_xmls_sc3ml. @alexgorb, I will copy over to GA-Transfer on Monday.

**Comment by basaks** [comment]
The updated events have `hypocenters`. Thanks @niketchhajed .
