### ISSUE TITLE
Move CWB waveform data to AWS and host it on SC3

### ISSUE THREAD

**Issue by niketchhajed** [GeoscienceAustralia/passive-seismic#70]
The following plan will be followed in the process of waveform data migration to AWS:

1. Lift and shift the waveform data from 1986 upto latest into the glacier managed service in AWS
2. Given that the density and size of data is different for different years, the CWB EC2 instances will be provisioned accordingly. Details and strategy are being discussed with @zhang01GA . Overall, the d2 EC2 instance type which is optimised for large storage will be explored for years that require disk sizes of 2TB plus.
3. Also, depending on the storage requirements for particular years, they may be grouped together into a single Seiscomp3 instance to take advantage of the d2 type offering.
4. An application ELB is being contemplated to fan out the incoming requests to appropriate EC2 instance based on the request parameters of the timewindow requested, specifically in case of dataselect fdsn queries.

More details will be shared with the team as they get ironed out ...

**Comment by zhang01GA** [comment]
Thanks Niket.
I think it is a good idea to piggyback seiscomp3 server for CWB server: combine the two servers into one BIG ec2 instance can save cloud cost and simplify admin operation. In this case the CWB is used as a transient.

**Comment by niketchhajed** [comment]
Waveform data for the years 2000, 2001 and 2002 have been ingested into a staging EC2 instance running SC3. Currently, data for 2003(about 138G) and 2013(1.1T) are being ingested. The 2013 is a test case for a large dataset to go through any issues we might face.

In parallel, the waveform data for the years that have been ingested has also been uploaded to glacier to prevent the need for any rsync in future. This will continue for subsequent years.

**Comment by niketchhajed** [comment]
The waveform data for the following years has been ingested into the corresponding VM mentioned:

2000 - 2006 -> niket_sc3_staging_2K_to_2K4
2012 -> niket_sc3_staging_2012
2007, 2013 -> niket_sc3_staging_2013

For the other years, the copying over to the CWB instances and ingestion into the SC3 instances is in progress ...

For some years, a significant number of days worth of waveform data seems to be missing in CWB archive. I am following up with @alexgorb and this issue will have to be addressed.

**Comment by niketchhajed** [comment]
The latest status is as follows:

2000 - 2006,2009 -> niket_sc3_stag_2K_to_2K6_2K9
2012 -> niket_sc3_staging_2012
2007, 2013 -> niket_sc3_staging_2K13_2K7
2010 - 2011 -> niket_sc3_stag_2K10_2K11
2014 -> niket_sc3_staging_2K14 (ongoing)
1986 - 1999 -> niket_sc3_stag_pre2K (ongoing)

**Comment by niketchhajed** [comment]
The waveform data is now available on a single instance in AWS. However, there is a limitation on the size of the root EBS volume that can be attached to an EC2 instance. The limit is 2TB and our seiscomp3 waveform archive sits in /opt/seiscomp3/var/lib/archive which happens to be the root volume on EC2 instance. This limitation is being worked around. Pasting the AWS doc for reference in future: https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/ebs-using-volumes.html.

**Comment by niketchhajed** [comment]
We can also configure SC3 to have the sdsarchive in a non-root volume location. In which case, we will have to then attach a new comment and then mount it in a new location and configure SC3 sdsarchive accordingly.

**Comment by niketchhajed** [comment]
The CWB archived waveform data for the years 1987 to 2017 is now available on a single Seiscomp3 instance which also has the station metadata and events metadata ingested. The waveform, event and station data can be consumed over an HTTP FDSN interface. Currently, it is available on the AWS instance: ec2-54-66-252-245.ap-southeast-2.compute.amazonaws.com:8081. At this point, if someone wants to consume this data for experimentation purpose, the IP address of the machine firing the query will have to be white-listed. 

Note: this the first cut of such an instance. It will undergo some improvements in terms of waveform data and station metadata.

**Comment by niketchhajed** [comment]
Also, the event metadata will be updated with the results from automatic s-pick extraction.

**Comment by niketchhajed** [comment]
Details of RF files location:
cleaned RFs - /g/data/ha3/niket/mtIsa_rf/ASDF/rfs/cleaned_RFs
raw RFs - /g/data/ha3/niket/mtIsa_rf/ASDF/rfs/raw_RFs
raw stream data - /g/data/ha3/niket/mtIsa_rf/ASDF/raw_stream_cleaned

Closing this task
