### ISSUE TITLE
Improvements/enhancements for the picking of P and S phases

### ISSUE THREAD

**Issue by BabakHejrani** [GeoscienceAustralia/passive-seismic#93]
Following issues have been discussed, 26 June 2018: 
==================================================
Procedure for Picking P- and S-wave, 
Rakib has tested zero-phase filter (two way filter) versus wavelet. 
The shapes are different but they both preserve the time, as we expect.
so, for now we just go with zero phase filter.
The filter is Butterworth. The order must be 2 (not checked). 

==================================================
Resample: We resample to dt=0.05 second after we filter the data. 

==================================================
Frequency bands: 
We pick all P-wave arrivals at the following frequencies: 
P-wave: 
0.5 - 2.0 Hz
0.3 - 4.0 Hz

S-wave:
0.05 - 0.2 Hz
0.05 - 1.0 Hz

**Comment by BabakHejrani** [comment]
Later, I would like to see the effect of 'Mixed filter' as well ... 
https://www.researchgate.net/publication/253046380_Analysis_and_repair_of_bias_in_existing_teleseismic_travel_time_databases

**Comment by niketchhajed** [comment]
The code changes are complete and we will organize and trigger the picking for all surveys and the archived permanent stations waveform data.

**Comment by niketchhajed** [comment]
The picking for bilby and mtIsa has been triggered ...

**Comment by niketchhajed** [comment]
The changes requested in this task have been implemented. Closing the issues.
